apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkyrie-hubot-deployment
  labels:
    app: hubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubot
  template:
    metadata:
      labels:
        app: hubot
    spec:
      containers:
        - name: hubot
          # image: gcr.io/thesis-ops-2748/valkyrie:USE_CIRCLE_CI_BUILDS
          env:
            - name: HUBOT_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: discord_api_token
            - name: HUBOT_MATRIX_USER
              value: "@valkyrie:thesis.co"
            - name: HUBOT_MATRIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: matrix_valkyrie_password
            - name: HUBOT_MATRIX_HOST_SERVER
              value: "https://thesisco.ems.host"
            - name: HUBOT_HOST
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: host
            - name: HUBOT_SCHEDULE_DEBUG
              value: "1"
            - name: HUBOT_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: hubot_webhook_url
            - name: HUBOT_WEBHOOK_AUTH
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: hubot_webhook_auth
            - name: HUBOT_N8N_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: hubot_n8n_webhook
            - name: RELEASE_NOTIFICATION_ROOM
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: valkyrie_alert_flow
            - name: SUGGESTION_ALERT_ROOM # Name of room for suggestion posts
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: valkyrie_alert_flow
            - name: REDIS_URL
              value: $(VALKYRIE_REDIS_SERVICE_PORT)
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: github_client_secret
            - name: FIGMA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: figma_api_token
            - name: IMGFLIP_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: imgflip_api_username
            - name: IMGFLIP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: imgflip_api_password
            - name: ZOOM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: zoom_api_key
            - name: ZOOM_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: valkyrie-hubot
                  key: zoom_api_secret
            - name: ZOOM_EXPECTED_MEETING_DURATION
              value: "60"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
